"""add bookmark fk and student unique constraint

Revision ID: ef2035648934
Revises: 640e870a7932
Create Date: 2026-05-21 14:18:14.168563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2035648934'
down_revision: Union[str, Sequence[str], None] = '640e870a7932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookmarks', 'courses', ['course_id'], ['course_id'])
    op.create_unique_constraint('uq_student_per_course', 'students', ['moodle_user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_per_course', 'students', type_='unique')
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    # ### end Alembic commands ###
